services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datadrive
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./datadrive.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password --performance-schema=ON --innodb-buffer-pool-size=256M
    networks:
      - datadrive-network

  memcached:
    image: memcached:1.6
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - datadrive-network

  datadrive-app:
    container_name: datadrive-app
    build:
      context: .
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: datadrive
      DB_USER: user
      DB_PASSWORD: password
      JWT_SECRET: buhbuhbuhbuh
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
    ports:
      - "8000:8000"
    networks:
      - datadrive-network

  datadrive-ui:
    container_name: datadrive-ui
    build:
      context: ./frontend/
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000
    ports:
      - "3000:80"
    networks:
      - datadrive-network

volumes:
  db_data:

networks:
  datadrive-network:
    driver: bridge
